version: '3.8'
services:
  mongo:
    image: mongo:4.1.8-xenial
    ports:
      - "27018:27017"
    volumes:
      - ./mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: btpn